/*
https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

package main

import (
	"fmt"
)

func main() {
	var limit int = 4000000
	var sum int
	var i int

	for fib(i) < limit {
		fmt.Printf("%d ", fib(i))
		if isEven(fib(i)) {
			sum += fib(i)
		}
		i++
	}

	fmt.Printf("\n%d\n", sum)
}

func fib(i int) (ret int) {
	if i == 0 {
		return 0
	}
	if i == 1 {
		return 1
	}
	return fib(i-1) + fib(i-2)
}

func isEven(i int) bool {
	return i%2 == 0
}
