[package]
name = "project-euler-004"
version = "0.1.0"
authors = ["Robbie Blaine <robbieblaine.rb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
